name: Ed Johnson
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
sass:
    sass_dir: _sass
    style: compressed
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
   - jekyll-sitemap
   - jekyll-paginate
